=== daggersearch/daggerheart-data/_schemas/domain-cards.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://daggersearch.com/schemas/domain-cards.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "$ref": "./common/id.schema.json"
      },
      "name": {
        "$ref": "./common/localized-string.schema.json"
      },
      "domain": {
        "$ref": "./common/domain.schema.json"
      },
      "type": {
        "type": "string",
        "enum": ["ABILITY", "SPELL", "GRIMOIRE"]
      },
      "level": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10
      },
      "recallCost": {
        "type": "integer",
        "minimum": 0
      },
      "features": {
        "type": "array",
        "items": {
          "$ref": "./common/feature.schema.json"
        }
      }
    },
    "required": [
      "id",
      "name",
      "domain",
      "type",
      "level",
      "recallCost",
      "features"
    ],
    "additionalProperties": false
  }
}

=== daggersearch/daggerheart-data/the_void/domain-cards.json
[
  {
    "id": "the_void_domain_card_blighting_strike",
    "name": { "en-US": "Blighting Strike" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 1,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Make a Spellcast Roll against a target within Far range. On a success, the target takes d6+1 magic damage using your Proficiency and the next time the target deals damage to an ally, it is reduced by half. If you succeed with Fear, the target instead takes d10+1 magic damage using your Proficiency."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_hideous_retribution",
    "name": { "en-US": "Hideous Retribution" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 2,
    "recallCost": 2,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "When an ally within Close range takes damage from a target you can see, you can make a Spellcast Reaction Roll against the target. On a success, mark a Stress to deal them d6 magic damage using your Proficiency."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_shared_trauma",
    "name": { "en-US": "Shared Trauma" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 3,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "You can transfer suffering from one creature to another. Once per rest, mark any number of Hit Points on a willing creature within Melee range to clear an equal number of Hit Points on another willing creature within Melee range. You can choose yourself in place of either creature."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_voice_of_dread",
    "name": { "en-US": "Voice of Dread" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 1,
    "recallCost": 0,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "You can magically speak directly into the ears of a creature you can see. To torment them with your words, make a Spellcast Roll against them. On a success, they must mark a Stress and become temporarily Vulnerable."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_siphon_essence",
    "name": { "en-US": "Siphon Essence" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 2,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Make a Spellcast Roll against a target within Very Close range. On a success, once per long rest, the target takes d20 magic damage using your Proficiency. You clear a number of Hit Points equal to the number of Hit Points the target marked from this attack. On a success with Fear, you gain a +1 bonus to your Proficiency for this attack."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_chains_of_affliction",
    "name": { "en-US": "Chains of Affliction" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 4,
    "recallCost": 2,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Mark 2 Stress to temporarily Chain a target within Close range. When a Chained creature deals damage, the target of their attack reduces the number of Hit Points they mark by one. You canâ€™t have more than one creature Chained at a time."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_umbral_veil",
    "name": { "en-US": "Umbral Veil" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 1,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Once per rest, when you roll with Fear, you can spend any number of Hope to place an equal number of tokens on this card, encasing yourself in a shadowy energy. After an attack roll is made against you, you can spend any number of tokens to give the attack roll a -1 penalty per token. On your next rest, remove all tokens from this card."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_terrify",
    "name": { "en-US": "Terrify" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 3,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Make a Spellcast Roll against a target within Far range. On a success, the target marks 1d4 Stress and you can choose to make the target run one range away from you (Close to Far, Far to Very Far, etc). On a success with Fear, the target becomes temporarily Vulnerable."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_summon_horror",
    "name": { "en-US": "Summon Horror" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 4,
    "recallCost": 2,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Make a Spellcast Roll against a target within Far range. Ona success, spend a Hope to call forth an otherworldly creature to attack them and deal d10 magic damage using your Proficiency. The target must succeed on a Reaction Roll (12) to steel themselves from the horror or mark 1d4 Stress."
            }
          },
          {
            "paragraph": {
              "en-US": "After making the attack, the creature dissipates."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_spectral_mist",
    "name": { "en-US": "Spectral Mist" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 5,
    "recallCost": 0,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Mark a Stress to summon an eerie mist that turns you and any targets within Close range momentarily incorporeal. While a creature is incorporeal, they can move through solid objects and are immune to physical damage. A creature becomes corporeal again after they pass through a solid object or make an action roll. Otherwise, this effect drops at the end of the scene."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_dire_strike",
    "name": { "en-US": "Dire Strike" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 5,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "After making a successful attack, you can spend 2 Hope to leach power from the target. For each Hit Point your target marked from this attack, the GM loses a Fear."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_jump_scare",
    "name": { "en-US": "Jump Scare" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 6,
    "recallCost": 0,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "When you deal magic damage to a target, you can marka Stress to immediately teleport into Melee range of them. When you do, they become Vulnerable until they mark one or more Hit Points."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_dread_touched",
    "name": { "en-US": "Dread-Touched" },
    "domain": "DREAD",
    "type": "ABILITY",
    "level": 7,
    "recallCost": 2,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "When 4 or more of the domain cards in your loadout are from the Dread domain, gain the following benefits:"
            }
          },
          {
            "list": [
              {
                "en-US": "When you succeed with Fear, you can mark 2 Stress to prevent the GM from gaining a Fear."
              },
              {
                "en-US": "Once per rest, when making an action roll, you can add a +1 bonus to the roll for each Fear token the GM has stored."
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_dark_army",
    "name": { "en-US": "Dark Army" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 8,
    "recallCost": 2,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "Make a Spellcast Roll (14). Once per long rest, on a success you can summon a group of fiends that surround and move with you. Place 8 tokens on this card. When you deal damage to a target within Very Close range, you can spend a token to increase it by +1d8. Additionally, when you take damage, you can spend a token to reduce it by 1d8. Each time you spend a token, a fiend acts on your behalf, then disappears."
            }
          },
          {
            "paragraph": {
              "en-US": "Remove all tokens from this card on your next rest."
            }
          }
        ]
      }
    ]
  },
  {
    "id": "the_void_domain_card_eldritch_flesh",
    "name": { "en-US": "Eldritch Flesh" },
    "domain": "DREAD",
    "type": "SPELL",
    "level": 8,
    "recallCost": 1,
    "features": [
      {
        "description": [
          {
            "paragraph": {
              "en-US": "You embody the darkness you have dallied with. When this card is in your loadout:"
            }
          },
          {
            "list": [
              {
                "en-US": "Gain a +1 bonus to your damage thresholds for each Stress you have marked."
              },
              {
                "en-US": "When you roll with Fear, you can spend 2 Hope to clear an Armor Slot."
              }
            ]
          }
        ]
      }
    ]
  },
  {
